import { AuthOptions, getServerSession } from 'next-auth';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';

import Navigation from '@/components/navigation/navigation';
import { ThemeProvider } from '@/components/theme-provider';
import { authOptions } from '@/auth/authOptions';
import Providers from '@/components/providers';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions as AuthOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Providers session={session}>
            <Navigation />
            {children}
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
